"""TenantId AutoGen

Revision ID: 1a5ddbd944d1
Revises: 0c4449e8151e
Create Date: 2024-11-13 16:16:18.308358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a5ddbd944d1'
down_revision: Union[str, None] = '0c4449e8151e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
