"""TenantId AutoGen

Revision ID: 48ec14bc84a7
Revises: 1a5ddbd944d1
Create Date: 2024-11-13 16:17:30.548496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48ec14bc84a7'
down_revision: Union[str, None] = '1a5ddbd944d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
