"""Ajout de la sequence

Revision ID: ee840485863f
Revises: 48ec14bc84a7
Create Date: 2024-11-13 16:20:10.944323

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee840485863f'
down_revision: Union[str, None] = '48ec14bc84a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SEQUENCE tenant_id_seq START WITH 1000")
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP SEQUENCE tenant_id_seq")
    pass
    # ### end Alembic commands ###
